### ISSUE TITLE
Is it possible to enumerate the values for ENUM-like fields in ipdb file?

### ISSUE THREAD

**Issue by t-bzhan** [ipipdotnet/ipdb-go#12]
Is it possible to enumerate the values for those ENUM-like fields like region_name, city_name, isp_domain in the ipdb file, we found that is pretty useful as we need to map these values to our own data model.
![image](https://user-images.githubusercontent.com/61817681/117613515-9e5deb80-b199-11eb-93c7-8d268724ac77.png)

**Comment by ipipdotnet** [comment]
db.Fields()  list fields
