### ISSUE TITLE
Why canceling the db.Reload() function on tag v1.1.0?

### ISSUE THREAD

**Issue by SgtDaJim** [ipipdotnet/ipdb-go#3]
Just curious.

**Comment by ipipdotnet** [comment]
We will update a new version as soon as possible @SgtDaJim

**Comment by ipipdotnet** [comment]
@SgtDaJim v1.2.0

**Comment by SgtDaJim** [comment]
Nice. So the cancel is just a mistake?

**Comment by ipipdotnet** [comment]
incorrect operation
 
 
------------------ Original ------------------
From: "SgtDaJim"; 
Date: 2019年3月19日(星期二) 晚上6:57
To: "ipipdotnet/ipdb-go"; 
Cc: "ipipdotnet"; "Comment"; 
Subject: Re: [ipipdotnet/ipdb-go] Why canceling the db.Reload() function on tag v1.1.0? (#3)

 

Nice. So the cancel is just a mistake?
