### ISSUE TITLE
占用过多内存

### ISSUE THREAD

**Issue by laokiea** [ipipdotnet/ipdb-go#9]
我们的服务部署在k8s上，使用后pods的内存增加了300多M，出现这个现象是使用的姿势不对吗
`ipdbPath := os.Getenv("IP_CITY_PATH")`
`_ipdb, _ := ipdb.NewCity(ipdbPath)`
`ipInfo, _ := _ipdb.FindInfo(lastIp, "CN")`

**Comment by ipipdotnet** [comment]
ipdbPath 这个路径指向的文件大小多大  @laokiea
